### ISSUE TITLE
Can't use region "Limburg-Zuid"

### ISSUE THREAD

**Issue by DieterKoblenz** [gvanlee/AlarmeringDroid-for-Homey#1]
When I select a region (in my example Limburg-Zuid) it does not pick up any P2000 messages. When I don't use all regions it picks up all messages (I believe including Limburg-Zuid).

**Comment by gvanlee** [comment]
Good call. There was a problem in the "region" filter. This has been fixed in the latest release that will be sent to your Homey in 1-2 days.

**Comment by DieterKoblenz** [comment]
Perfect! Thanks. Great app btw!
