### ISSUE TITLE
Feed down for day

### ISSUE THREAD

**Issue by hvhol** [gvanlee/AlarmeringDroid-for-Homey#10]
For several days the feed is down
Are there issues or is it over with AlarmeringDroid for hoemy ?

**Comment by hvhol** [comment]
https://alarmeringdroid.nl/livemonitor/VLAARDINGEN have good results but....

https://beta.alarmeringdroid.nl/livemonitor/VLAARDINGEN have stopt since 28-05-2019 this is exactly what i see in the Homey app it is down for days

**Comment by gvanlee** [comment]
Duplicate issue.
