### ISSUE TITLE
Repeating Alarms

### ISSUE THREAD

**Issue by WesRos** [gvanlee/AlarmeringDroid-for-Homey#2]
It was the second time in almost 2 month, that a alarm is repeating. The first time restarting Homey helps. The second time after restarting Homey the alarm from 2 day ago is repeating.
Now I've switch off the AlarmeringDroid in the setting menu.

**Comment by gvanlee** [comment]
I noticed myself too. I think it has to do with the scanner going offline for some time (those damn windowsupdates seem impossible to hold back in Windows 10).

Will look into it and fix it asap.
