### ISSUE TITLE
Repeating Messages

### ISSUE THREAD

**Issue by hvhol** [gvanlee/AlarmeringDroid-for-Homey#4]
with every messaging it will repeat Continuous since , i remove and install it again but that does not work
--

**Comment by gvanlee** [comment]
I seem to have the same problem now, so I will look into it again.

**Comment by gvanlee** [comment]
Version 1.1.5 should address this problem, it's on its way to the app store.

**Comment by hvhol** [comment]
Hey Gabri i have download 1.1.5 and it seems to work , thnx for your support and for the great App
