### ISSUE TITLE
feed down?

### ISSUE THREAD

**Issue by maikrovers** [gvanlee/AlarmeringDroid-for-Homey#9]
Hello,
since yesterday morning 28-05-2019 I do not get any messages anymore. Rebooted everything but without luck. Is there anything with the feed?
kind regards, Maik

**Comment by ETVenlo** [comment]
I think the api is down. Because I have the same problem. Didn't get any messages anymore.

**Comment by hvhol** [comment]
Me Too reboot won't help
Still by you maikrovers and ETVenlo?

**Comment by maikrovers** [comment]
Still no go... :(

**Comment by hvhol** [comment]
have you tried this?:

https://alarmeringdroid.nl/livemonitor/VLAARDINGEN have good results but....

https://beta.alarmeringdroid.nl/livemonitor/VLAARDINGEN have stopt since 28-05-2019 this is exactly what i see in the Homey app it is down for days

For your town ?

**Comment by maikrovers** [comment]
You are completely right! Beta shows excactly my last result....
Nice find out!
Now we need someone to fix it...;)

**Comment by hvhol** [comment]
I'm just receiving a feed on Homey , ik think someone is fixing it ;-)
Are there alternatives for Homey ,? i'm jusing this a lot .....

**Comment by gvanlee** [comment]
After aower outage, the beta site (which is used by this app) was not restarted properly. That issue has been fixed, so this is fixed too.

**Comment by maikrovers** [comment]
Aaahhh perfect! Thanx very much!

**Comment by hvhol** [comment]
SUper working great ! thnx
